import Link from "next/link";
export default function ResumeView({locale}:{locale:string}){
 const tr=locale==="tr";
 const projects=[
 {name:"YAS / PAS",status:"Prototype",description:tr?"Çevrimdışı yüz tanıma tabanlı personel devam takip sistemi. Serdivan Belediyesinde beta testleri gerçekleştirildi.":"Offline face-recognition attendance system, beta-tested at Serdivan Municipality."},
 {name:"SAYAS",status:"Discontinued",description:tr?"Ziyaretçi sayma amaçlı bilgisayarlı görü uygulaması. Gerçek ortamda beta testlerinin ardından geliştirilmesi durduruldu.":"Computer-vision visitor counter. Development discontinued following real-world beta tests."},
 {name:"EKAS",status:"Prototype",description:tr?"Bilgisayarlı görü ve Raspberry Pi ile emniyet kemeri tespitine yönelik prototip.":"Seat-belt detection prototype using computer vision and Raspberry Pi."},
 {name:"Albastı",status:"In Development",description:tr?"Bilişsel mimari ve akıllı sistemler üzerine tasarladığım uzun vadeli kişisel proje.":"A long-term personal project exploring cognitive architecture and intelligent systems."}
 ];
 return <div className="resume-page">
  <div className="resume-heading"><div><div className="eyebrow">{tr?"PROFİL & ÖZGEÇMİŞ":"PROFILE & RESUME"}</div><h1>Bedirhan Bayram</h1><p className="resume-subtitle">{tr?"Bilgisayar Mühendisi":"Computer Engineer"}</p></div><a className="button primary resume-download" href="/Bedirhan_Bayram_CV.pdf" download>{tr?"PDF CV İndir":"Download PDF CV"} ↓</a></div>
  <div className="resume-layout">
   <aside className="resume-aside">
    <section className="resume-panel"><h2>{tr?"İletişim":"Contact"}</h2><a href="mailto:bedirhanbayram.bb@gmail.com">bedirhanbayram.bb@gmail.com</a><a href="https://github.com/bed1rhan">github.com/bed1rhan ↗</a><a href="https://instagram.com/han.bayram_">@han.bayram_ ↗</a><p>{tr?"Sakarya, Türkiye":"Sakarya, Türkiye"}</p></section>
    <section className="resume-panel"><h2>{tr?"Teknik Alanlar":"Technical Areas"}</h2><div className="resume-chips">{["Python","C","C++","Computer Vision","OpenCV","Raspberry Pi","AI Systems","Git"].map(s=><span key={s}>{s}</span>)}</div></section>
    <section className="resume-panel"><h2>{tr?"Diller":"Languages"}</h2><div className="resume-facts"><div><strong>{tr?"Türkçe":"Turkish"}</strong><span>{tr?"Ana dil":"Native"}</span></div><div><strong>{tr?"İngilizce":"English"}</strong><span>C2</span></div><div><strong>{tr?"İspanyolca":"Spanish"}</strong><span>A2</span></div></div></section>
    <section className="resume-panel"><h2>{tr?"Güçlü Yönler":"Strengths"}</h2><div className="resume-chips">{(tr?["Liderlik","Takım çalışması","Yaratıcılık","İnisiyatif","Araştırma","Kültürlerarası iletişim"]:["Leadership","Teamwork","Creativity","Initiative","Research","Cross-cultural communication"]).map(s=><span key={s}>{s}</span>)}</div></section>
   </aside>
   <div className="resume-main">
    <section className="resume-block"><div className="resume-block-label">{tr?"HAKKIMDA":"PROFILE"}</div><h2>{tr?"Mühendislik, merak ve üretim.":"Engineering, curiosity and building."}</h2><p>{tr?"Sakarya Üniversitesinde Bilgisayar Mühendisliği eğitimi alıyorum. Yapay zekâ ve görüntü işleme teknolojilerine özellikle ilgi duyuyorum. Yazılımın fiziksel dünyayla buluştuğu robotik ve akıllı sistemler, ayrıca tersine mühendislik kariyerimde keşfetmek istediğim alanlar arasında.":"I study Computer Engineering at Sakarya University, with a particular interest in artificial intelligence and computer vision. I'm also drawn to robotics, reverse engineering and systems that connect software with the physical world."}</p><p>{tr?"Projelerimin çoğunu bağımsız olarak geliştirdim. Bunun yanında ekip çalışmasından, sorumluluk almaktan ve farklı insanlarla fikir üretmekten keyif alıyorum.":"I've developed most of my projects independently, while also enjoying collaboration, taking responsibility and exchanging ideas with others."}</p></section>
    <section className="resume-block"><div className="resume-block-label">{tr?"KİŞİSEL YOLCULUK":"PERSONAL JOURNEY"}</div><p>{tr?"2003 yılında Trabzon’da doğdum. Üniversite eğitimim için Sakarya’ya taşındım. Farklı şehirlerde ve kültürlerde edindiğim deneyimler, yeni insanlarla tanışma ve dünyayı keşfetme isteğimi besliyor.":"I was born in Trabzon in 2003 and moved to Sakarya for university. Living in different cities has strengthened my curiosity about people, cultures and the wider world."}</p></section><section className="resume-block"><div className="resume-block-label">{tr?"EĞİTİM":"EDUCATION"}</div><div className="resume-entry"><div className="resume-entry-meta">{tr?"Devam ediyor":"Ongoing"}</div><div><h3>{tr?"Sakarya Üniversitesi":"Sakarya University"}</h3><p>{tr?"Bilgisayar Mühendisliği · Lisans öğrencisi":"Computer Engineering · Undergraduate student"}</p></div></div></section>
    <section className="resume-block"><div className="resume-block-label">{tr?"SEÇİLİ PROJELER":"SELECTED PROJECTS"}</div><div className="resume-projects">{projects.map(p=><div className="resume-project" key={p.name}><div className="resume-project-head"><h3>{p.name}</h3><span className={"status status-"+(p.status==="In Development"?"development":p.status.toLowerCase())}>{p.status}</span></div><p>{p.description}</p></div>)}</div><Link className="resume-inline-link" href={`/${locale}/projects/`}>{tr?"Tüm projeler":"All projects"} ↗</Link></section>
    <section className="resume-block"><div className="resume-block-label">{tr?"SERTİFİKALAR":"CERTIFICATIONS"}</div><div className="resume-entry"><div className="resume-entry-meta">2020</div><div><h3>Entrepreneurial Skills Pass (ESP)</h3><p>JA Europe · EUROCHAMBRES · CSR Europe</p><p>{tr?"GençBizz Trabzon programı kapsamında girişimcilik, ekip çalışması, işletme, ekonomi ve finans alanlarında edinilen becerileri belgeleyen uluslararası sertifika.":"International certificate recognizing entrepreneurship, teamwork, business, economics and financial literacy skills through the GençBizz Trabzon programme."}</p><span className="resume-cert-note">{tr?"10 Eylül 2020 · Trabzon":"10 September 2020 · Trabzon"}</span></div></div></section>
    <section className="resume-block"><div className="resume-block-label">{tr?"İLGİ ALANLARI":"INTERESTS"}</div><p>{tr?"Oyun geliştirme, siber güvenlik, yeni teknolojiler, yabancı dil öğrenimi ve kültürlerarası iletişim. Seyahat etmeyi, kısa yazılar kaleme almayı ve kitaplar üzerinde çalışmayı seviyorum.":"Game development, cybersecurity, emerging technologies, language learning and cross-cultural communication. I enjoy travelling, writing short pieces and writing books."}</p></section>
   </div>
  </div>
 </div>
}